# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_name', models.CharField(default=None, max_length=32, null=True)),
                ('player_side', models.BooleanField(default=True)),
                ('runner_id', models.IntegerField(default=0)),
                ('runner_score', models.IntegerField(default=0)),
                ('corp_name', models.CharField(default=None, max_length=32, null=True)),
                ('corp_id', models.IntegerField(default=0)),
                ('corp_score', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=True)),
                ('win_type', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date played')),
                ('exact_match', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('faction_code', models.CharField(max_length=32)),
                ('side_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_side', models.BooleanField(default=True)),
                ('player_id', models.IntegerField(default=0)),
                ('player_score', models.IntegerField(default=0)),
                ('opp_id', models.IntegerField(default=0)),
                ('opp_score', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=True)),
                ('win_type', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date played')),
                ('exact_match', models.IntegerField(default=1)),
            ],
        ),
    ]
