# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170405_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerGame',
        ),
        migrations.RemoveField(
            model_name='game',
            name='opponent_username',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_side',
        ),
    ]
