# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170119_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_side', models.BooleanField(default=True)),
                ('player_id', models.IntegerField(default=0)),
                ('player_score', models.IntegerField(default=0)),
                ('opp_id', models.IntegerField(default=0)),
                ('opp_score', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=True)),
                ('win_type', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date played')),
                ('online', models.BooleanField(default=False)),
                ('exact_match', models.IntegerField(default=1)),
            ],
        ),
    ]
