# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_playergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(verbose_name='date played'),
        ),
    ]
