# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170517_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='runs',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
