# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
